In [20]:
import numpy as np
import pandas as pd 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score , roc_curve , roc_auc_score

# ROC AND AUC 

Generally ROC (curve) is used to find out the correct thresold of probablity value so that we can classify the class perfectly , by deafult we assume the thresold is 0.5(for binary class classification ) , means if prob is greater than 0.5 then the predicted class for given instance is 1 , and if less then 0.5 then predicted class is 0 . but in some probelm (like email spam classifier , or churn rate prediction at some OTT) , we want to be so sure about positive class , so in that case we increase the thresold of classification , means if predicted prob is greater than thresold then only predict the class 1 , otherwise 0 . But we do not Know what should be thresold value , means we cant set thresold very high and also very less. ROC helps to find out optimal value of thresold . 

Here in ROC we plot the curve between TPR(True Positive rate) also called Benifits Vs FPR(False Positive Rate) also called Cost  , for each thresold value . And we find that Thresold where TPR (Benifit) is close to 1 and FPR is close to 0. \

 X-axis = FPR , Y_axis = TPR

TPR = True Positive / ( True Positive + False Negative)   , will varry between 0 to 1 \
FPR = False Positive / ( False Positive + True Negative)   , will varry between 0 to 1 

TPR should be close to 1 and FPR should be close to 0 , for good quality of classification .\

ROC is valid for binary class classification only 


In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')


In [22]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [23]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [24]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state=2)
X_train.shape , X_test.shape

((614, 8), (154, 8))

In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()  
x_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [26]:
lr = LogisticRegression(max_iter=1200)
lr.fit(x_train_scaled , y_train)

LogisticRegression(max_iter=1200)

In [27]:
y_pred = lr.predict(X_test_scaled)
print("accuracy_score" , accuracy_score(y_test,y_pred))

accuracy_score 0.7662337662337663


In [28]:
y_prob = lr.predict_proba(X_test_scaled)  # it will give matrix [ ]  , size = n_samples * n_class 

In [29]:
y_prob[0:10 , :] # First 10 samples prob distribution 

array([[0.94989067, 0.05010933],
       [0.82530925, 0.17469075],
       [0.90660355, 0.09339645],
       [0.74556489, 0.25443511],
       [0.3715061 , 0.6284939 ],
       [0.88398627, 0.11601373],
       [0.93301367, 0.06698633],
       [0.5823404 , 0.4176596 ],
       [0.95038344, 0.04961656],
       [0.43303282, 0.56696718]])

In [30]:
# Now lets calculate the probablity of class 1 (positive class ), that is 2nd column value for each samples
# we can assume any class as postive on the basis of problem , does not necessary that class 1 is positive class 
y_prob_positive = y_prob[:,1]
y_prob_positive

array([0.05010933, 0.17469075, 0.09339645, 0.25443511, 0.6284939 ,
       0.11601373, 0.06698633, 0.4176596 , 0.04961656, 0.56696718,
       0.34663231, 0.40971737, 0.69753565, 0.19828039, 0.0214474 ,
       0.82582892, 0.85793454, 0.03195066, 0.25099627, 0.89302546,
       0.95311586, 0.8296885 , 0.11642749, 0.44112127, 0.09002005,
       0.06881776, 0.64447307, 0.41643232, 0.17682894, 0.28296295,
       0.24593752, 0.44363844, 0.00967213, 0.24120036, 0.3667008 ,
       0.96019635, 0.33453649, 0.80121728, 0.2970304 , 0.05077273,
       0.18037685, 0.08696022, 0.41921846, 0.18675762, 0.03170779,
       0.04020777, 0.24558176, 0.43174056, 0.10653096, 0.38104112,
       0.99400217, 0.11322548, 0.39416142, 0.766472  , 0.37206733,
       0.46233145, 0.94791485, 0.41654922, 0.40287023, 0.04437377,
       0.38013692, 0.89700961, 0.87593027, 0.88280168, 0.3267866 ,
       0.0740778 , 0.94869452, 0.20399675, 0.26545769, 0.3617794 ,
       0.10735344, 0.08388764, 0.44437786, 0.09563801, 0.08691

In [31]:
fpr , tpr , thresold = roc_curve(y_test , y_prob_positive)  

# calculate False Positive rate , True Positive rate , and thresold

# corresponding to each thresold ( means if prob is greater than this value then class 1 (positive) , otherwise class 0)
# we will get one Flase Postive Rate , one True Positive Rate 

# True Positive rate = True Positive / ( True Positive + False Negative)
# False Positive rate = False positive / (False Positive + True Negative)

In [32]:
thresold       # it will be between 0 to 1 

array([       inf, 0.99400217, 0.96019635, 0.95311586, 0.82582892,
       0.766472  , 0.76492755, 0.67816096, 0.6631371 , 0.65651144,
       0.6284939 , 0.58184108, 0.57195904, 0.57070079, 0.52054392,
       0.50555618, 0.46886719, 0.46233145, 0.46126993, 0.44437786,
       0.44112127, 0.43863861, 0.41921846, 0.41643232, 0.40971737,
       0.39989907, 0.39729137, 0.38104112, 0.36795376, 0.32389188,
       0.31117418, 0.27164402, 0.27016507, 0.2634007 , 0.25443511,
       0.25099627, 0.24593752, 0.23526212, 0.23386702, 0.18037685,
       0.17557071, 0.14474917, 0.14037747, 0.12327783, 0.11902515,
       0.11601373, 0.11322548, 0.09002005, 0.08696022, 0.0214474 ,
       0.02082904, 0.0017339 ])

In [33]:
# ignore inf , it is from sklearn 

In [34]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresold)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresold[indices]],
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()

# Blue curve is ROC

In [35]:
# Now How to find Best Thresold value , we will see where tpr-fpr is maximum , corresponding to 
# that index we will find thersold

# Assume that fpr, tpr, thresholds have already been calculated
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresold[optimal_idx]
print("Optimal threshold is:", optimal_threshold)


Optimal threshold is: 0.3679537604198765


In [36]:
# AUC Is Nothing but area under ROC curve , if area is close to 1 then the model is very good 
# we can compare 2 model using AUC , greater the AUC better the model 

# AUC score should be more than 0.5 , if less or equal then means model is giving random guess

In [37]:
auc_score = roc_auc_score(y_test , y_prob_positive)
print(auc_score)

0.7940876656472986


In [38]:
# Lets see for SVM and LogisticRegression 

import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler


# Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_scores = lr_model.predict_proba(X_test)[:,1]

# SVM model
svm_model = SVC(probability=True)
svm_model.fit(x_train_scaled, y_train)
svm_scores = svm_model.predict_proba(X_test_scaled)[:,1]

# Generate ROC curve data for logistic regression model
lr_fpr, lr_tpr, lr_thresholds = roc_curve(y_test, lr_scores)
lr_auc = roc_auc_score(y_test, lr_scores)

# Generate ROC curve data for SVM model
svm_fpr, svm_tpr, svm_thresholds = roc_curve(y_test, svm_scores)
svm_auc = roc_auc_score(y_test, svm_scores)


print("AUC score LogosticRegression" , lr_auc)
print("AUC score LogosticRegression" , svm_auc)

# Generate a trace for the Logistic Regression ROC curve
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()

AUC score LogosticRegression 0.7934760448521917
AUC score LogosticRegression 0.8120285423037716
